apiVersion: v1
kind: PersistentVolume
metadata:
 name: my-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce  
  hostPath: 
    path : /home/tchandru369/shop-manage/src/main/resources
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce  
  resources:
    requests:
      storage: 1Gi