server:
  port: 8083
  ssl:
    key-store: /app/resources/merchantapp.p12
    key-store-password: ${SSL_CERT_PASSWORD}
    key-store-type: PKCS12
    key-alias: 1
spring:
  application:
    name: management-app
  security:
    enabled: true
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: chanper369@gmail.com
    password: ${SMTP_MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  management:
    security:
      enabled: false

security:
  ignored: "/**"
  basic:
    enabled: false
  jwt:
    secret-key: ${JWT_KEY_VALUE}
    expiration-time: 3600000  # 1 hour in milliseconds

billreport:
  path: /app/storage/BillingReports/

brevo:
  api:
    url: https://api.brevo.com/v3/smtp/email
    key: ${BREVO_API_KEY}