create database IF NOT EXISTS managementdb;

USE managementdb; 

CREATE TABLE CMP_MILK_PROD_DTLS(
	COM_NAME VARCHAR(20),
	PROD_TYPE VARCHAR(20),
	PROD_NAME VARCHAR(50)	
);

CREATE TABLE CON_STATE_CITY(
	country_names VARCHAR(50),
	state_names VARCHAR(100),
	city_names VARCHAR(150)
);


INSERT INTO CMP_MILK_PROD_DTLS(COM_NAME,PROD_TYPE,PROD_NAME) VALUES('Aavin','Gold Milk','1000ml');
INSERT INTO CMP_MILK_PROD_DTLS(COM_NAME,PROD_TYPE,PROD_NAME) VALUES('Aavin','Gold Milk','500ml');
INSERT INTO CMP_MILK_PROD_DTLS(COM_NAME,PROD_TYPE,PROD_NAME) VALUES('Aavin','Delite','500ml');
INSERT INTO CMP_MILK_PROD_DTLS(COM_NAME,PROD_TYPE,PROD_NAME) VALUES('Aavin','SM','200ml');
INSERT INTO CMP_MILK_PROD_DTLS(COM_NAME,PROD_TYPE,PROD_NAME) VALUES('Aavin','Curd','500ml');
INSERT INTO CMP_MILK_PROD_DTLS(COM_NAME,PROD_TYPE,PROD_NAME) VALUES('Aavin','Curd','180ml');
INSERT INTO CMP_MILK_PROD_DTLS(COM_NAME,PROD_TYPE,PROD_NAME) VALUES('Dodla','FC','1000ml');
INSERT INTO CMP_MILK_PROD_DTLS(COM_NAME,PROD_TYPE,PROD_NAME) VALUES('Dodla','FC','500ml');
INSERT INTO CMP_MILK_PROD_DTLS(COM_NAME,PROD_TYPE,PROD_NAME) VALUES('Dodla','SM','1000ml');
INSERT INTO CMP_MILK_PROD_DTLS(COM_NAME,PROD_TYPE,PROD_NAME) VALUES('Dodla','SM','500ml');
INSERT INTO CMP_MILK_PROD_DTLS(COM_NAME,PROD_TYPE,PROD_NAME) VALUES('Dodla','SM','180ml');
INSERT INTO CMP_MILK_PROD_DTLS(COM_NAME,PROD_TYPE,PROD_NAME) VALUES('Dodla','TM','170ml');
INSERT INTO CMP_MILK_PROD_DTLS(COM_NAME,PROD_TYPE,PROD_NAME) VALUES('Dodla','Curd','500ml');
INSERT INTO CMP_MILK_PROD_DTLS(COM_NAME,PROD_TYPE,PROD_NAME) VALUES('Dodla','Curd','130ml');
INSERT INTO CMP_MILK_PROD_DTLS(COM_NAME,PROD_TYPE,PROD_NAME) VALUES('Dodla','Butter Milk','200ml');
INSERT INTO CMP_MILK_PROD_DTLS(COM_NAME,PROD_TYPE,PROD_NAME) VALUES('Athava','SM','500ml');
INSERT INTO CMP_MILK_PROD_DTLS(COM_NAME,PROD_TYPE,PROD_NAME) VALUES('Athava','SM','120ml');




INSERT INTO CON_STATE_CITY(country_names,state_names,city_names) VALUES('INDIA','TAMIL NADU','SALEM');
INSERT INTO CON_STATE_CITY(country_names,state_names,city_names) VALUES('INDIA','TAMIL NADU','DHARMAPURI');
INSERT INTO CON_STATE_CITY(country_names,state_names,city_names) VALUES('INDIA','TAMIL NADU','VILUPURAM');
INSERT INTO CON_STATE_CITY(country_names,state_names,city_names) VALUES('INDIA','TAMIL NADU','TINDIVANAM');
